### ISSUE TITLE
ERROR: recursion is detected during loading of "cv2" binary extensions

### ISSUE THREAD

**Issue by Rewarp** [virtuber/openvtuber#108]
I am attempting to build and run from the [docker specific instructions](https://openvtuber.com/docs/docker). When the program crashed at the step:

`docker run --rm --device=/dev/video0:/dev/video0 --network host openvtuber-server`

I then initiated the docker image `openvtuber-server` directly with `docker run -it openvtuber-server` and saw the same error.

The full log from running the command:

```bash
['/app/src/dist/__main__/base_library.zip', '/app/src/dist/__main__/cv2', '/app/src/dist/__main__/lib-dynload', '/app/src/dist/__main__']
Traceback (most recent call last):
  File "openvtuber/__main__.py", line 1, in <module>
    import openvtuber.lib as cli
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "openvtuber/lib.py", line 2, in <module>
    import cv2
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "importlib/__init__.py", line 127, in import_module
    applySysPathWorkaround = True
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "cv2/__init__.py", line 76, in bootstrap
    raise ImportError('ERROR: recursion is detected during loading of "cv2" binary extensions. Check OpenCV installation.')
ImportError: ERROR: recursion is detected during loading of "cv2" binary extensions. Check OpenCV installation.
[7] Failed to execute script '__main__' due to unhandled exception!
```

**Comment by AviciiLove-Github** [comment]
idk how i solved this problem,but i changed my opencv-python's version.
i use this code`pip install -v opencv-python==4.5.5.64(any version)`
and then i can package it successfully

{there is another method,is to download official files from [link](https://opencv.org/releases/)
decompress the file and then use code `pyinstaller -F xxx.py --paths="abs"(path u decompress)`}

if u have any issues,u can send me e-mail at aviciisong@foxmail.com
